"use client";

import { useState } from "react";

// Full Periodic Table Data
const periodicTable = [
  {
    number: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: 1.008,
    category: "Nonmetal",
    electronConfig: "1s¹",
    group: 1,
    period: 1,
    block: "s",
    phase: "Gas",
    density: 0.00008988,
    meltingPoint: 14.01,
    boilingPoint: 20.28,
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    atomicMass: 4.0026,
    category: "Noble Gas",
    electronConfig: "1s²",
    group: 18,
    period: 1,
    block: "s",
    phase: "Gas",
    density: 0.0001785,
    meltingPoint: 0.95,
    boilingPoint: 4.22,
  },
  {
    number: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: 6.94,
    category: "Alkali Metal",
    electronConfig: "[He] 2s¹",
    group: 1,
    period: 2,
    block: "s",
    phase: "Solid",
    density: 0.534,
    meltingPoint: 453.69,
    boilingPoint: 1603,
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicMass: 9.0122,
    category: "Alkaline Earth",
    electronConfig: "[He] 2s²",
    group: 2,
    period: 2,
    block: "s",
    phase: "Solid",
    density: 1.85,
    meltingPoint: 1560,
    boilingPoint: 2744,
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    atomicMass: 10.81,
    category: "Metalloid",
    electronConfig: "[He] 2s² 2p¹",
    group: 13,
    period: 2,
    block: "p",
    phase: "Solid",
    density: 2.34,
    meltingPoint: 2573,
    boilingPoint: 4200,
  },
  {
    number: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: 12.011,
    category: "Nonmetal",
    electronConfig: "[He] 2s² 2p²",
    group: 14,
    period: 2,
    block: "p",
    phase: "Solid",
    density: 2.267,
    meltingPoint: 3915,
    boilingPoint: 4300,
  }, // Sublimates
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: 14.007,
    category: "Nonmetal",
    electronConfig: "[He] 2s² 2p³",
    group: 15,
    period: 2,
    block: "p",
    phase: "Gas",
    density: 0.001251,
    meltingPoint: 63.15,
    boilingPoint: 77.36,
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: 15.999,
    category: "Nonmetal",
    electronConfig: "[He] 2s² 2p⁴",
    group: 16,
    period: 2,
    block: "p",
    phase: "Gas",
    density: 0.001429,
    meltingPoint: 54.36,
    boilingPoint: 90.188,
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: 18.998,
    category: "Halogen",
    electronConfig: "[He] 2s² 2p⁵",
    group: 17,
    period: 2,
    block: "p",
    phase: "Gas",
    density: 0.001696,
    meltingPoint: 53.53,
    boilingPoint: 85.03,
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    atomicMass: 20.18,
    category: "Noble Gas",
    electronConfig: "[He] 2s² 2p⁶",
    group: 18,
    period: 2,
    block: "p",
    phase: "Gas",
    density: 0.0008999,
    meltingPoint: 24.56,
    boilingPoint: 27.07,
  },
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: 22.99,
    category: "Alkali Metal",
    electronConfig: "[Ne] 3s¹",
    group: 1,
    period: 3,
    block: "s",
    phase: "Solid",
    density: 0.968,
    meltingPoint: 370.944,
    boilingPoint: 1156,
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: 24.305,
    category: "Alkaline Earth",
    electronConfig: "[Ne] 3s²",
    group: 2,
    period: 3,
    block: "s",
    phase: "Solid",
    density: 1.738,
    meltingPoint: 923,
    boilingPoint: 1363,
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminium",
    atomicMass: 26.982,
    category: "Post-transition Metal",
    electronConfig: "[Ne] 3s² 3p¹",
    group: 13,
    period: 3,
    block: "p",
    phase: "Solid",
    density: 2.7,
    meltingPoint: 933.47,
    boilingPoint: 2743,
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: 28.085,
    category: "Metalloid",
    electronConfig: "[Ne] 3s² 3p²",
    group: 14,
    period: 3,
    block: "p",
    phase: "Solid",
    density: 2.33,
    meltingPoint: 1687,
    boilingPoint: 3538,
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicMass: 30.974,
    category: "Nonmetal",
    electronConfig: "[Ne] 3s² 3p³",
    group: 15,
    period: 3,
    block: "p",
    phase: "Solid",
    density: 1.823,
    meltingPoint: 317.3,
    boilingPoint: 553,
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulfur",
    atomicMass: 32.06,
    category: "Nonmetal",
    electronConfig: "[Ne] 3s² 3p⁴",
    group: 16,
    period: 3,
    block: "p",
    phase: "Solid",
    density: 2.07,
    meltingPoint: 388.36,
    boilingPoint: 717.8,
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: 35.45,
    category: "Halogen",
    electronConfig: "[Ne] 3s² 3p⁵",
    group: 17,
    period: 3,
    block: "p",
    phase: "Gas",
    density: 0.003214,
    meltingPoint: 171.6,
    boilingPoint: 239.11,
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    atomicMass: 39.95,
    category: "Noble Gas",
    electronConfig: "[Ne] 3s² 3p⁶",
    group: 18,
    period: 3,
    block: "p",
    phase: "Gas",
    density: 0.001784,
    meltingPoint: 83.8,
    boilingPoint: 87.3,
  },
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    atomicMass: 39.098,
    category: "Alkali Metal",
    electronConfig: "[Ar] 4s¹",
    group: 1,
    period: 4,
    block: "s",
    phase: "Solid",
    density: 0.856,
    meltingPoint: 336.53,
    boilingPoint: 1032,
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicMass: 40.078,
    category: "Alkaline Earth",
    electronConfig: "[Ar] 4s²",
    group: 2,
    period: 4,
    block: "s",
    phase: "Solid",
    density: 1.55,
    meltingPoint: 1115,
    boilingPoint: 1757,
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    atomicMass: 44.955,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d¹ 4s²",
    group: 3,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 2.985,
    meltingPoint: 1814,
    boilingPoint: 3109,
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    atomicMass: 47.867,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d² 4s²",
    group: 4,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 4.506,
    meltingPoint: 1941,
    boilingPoint: 3560,
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    atomicMass: 50.942,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d³ 4s²",
    group: 5,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 6.11,
    meltingPoint: 2183,
    boilingPoint: 3680,
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    atomicMass: 51.996,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d⁵ 4s¹",
    group: 6,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 7.15,
    meltingPoint: 2180,
    boilingPoint: 2944,
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    atomicMass: 54.938,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d⁵ 4s²",
    group: 7,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 7.21,
    meltingPoint: 1519,
    boilingPoint: 2334,
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    atomicMass: 55.845,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d⁶ 4s²",
    group: 8,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 7.874,
    meltingPoint: 1811,
    boilingPoint: 3134,
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    atomicMass: 58.933,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d⁷ 4s²",
    group: 9,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 8.9,
    meltingPoint: 1768,
    boilingPoint: 3200,
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    atomicMass: 58.693,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d⁸ 4s²",
    group: 10,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 8.908,
    meltingPoint: 1728,
    boilingPoint: 3003,
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    atomicMass: 63.546,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d¹⁰ 4s¹",
    group: 11,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 8.96,
    meltingPoint: 1357.77,
    boilingPoint: 2835,
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicMass: 65.38,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d¹⁰ 4s²",
    group: 12,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 7.14,
    meltingPoint: 692.68,
    boilingPoint: 1180,
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicMass: 69.723,
    category: "Post-transition Metal",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p¹",
    group: 13,
    period: 4,
    block: "p",
    phase: "Solid",
    density: 5.91,
    meltingPoint: 302.91,
    boilingPoint: 2477,
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicMass: 72.63,
    category: "Metalloid",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p²",
    group: 14,
    period: 4,
    block: "p",
    phase: "Solid",
    density: 5.323,
    meltingPoint: 1211.4,
    boilingPoint: 3093,
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    atomicMass: 74.922,
    category: "Metalloid",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p³",
    group: 15,
    period: 4,
    block: "p",
    phase: "Solid",
    density: 5.727,
    meltingPoint: 1090,
    boilingPoint: 876,
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    atomicMass: 78.971,
    category: "Nonmetal",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁴",
    group: 16,
    period: 4,
    block: "p",
    phase: "Solid",
    density: 4.81,
    meltingPoint: 494,
    boilingPoint: 958,
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    atomicMass: 79.904,
    category: "Halogen",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁵",
    group: 17,
    period: 4,
    block: "p",
    phase: "Liquid",
    density: 3.1028,
    meltingPoint: 265.8,
    boilingPoint: 332.0,
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicMass: 83.798,
    category: "Noble Gas",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁶",
    group: 18,
    period: 4,
    block: "p",
    phase: "Gas",
    density: 0.003749,
    meltingPoint: 115.78,
    boilingPoint: 119.93,
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomicMass: 85.468,
    category: "Alkali Metal",
    electronConfig: "[Kr] 5s¹",
    group: 1,
    period: 5,
    block: "s",
    phase: "Solid",
    density: 1.532,
    meltingPoint: 312.46,
    boilingPoint: 961,
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    atomicMass: 87.62,
    category: "Alkaline Earth",
    electronConfig: "[Kr] 5s²",
    group: 2,
    period: 5,
    block: "s",
    phase: "Solid",
    density: 2.64,
    meltingPoint: 1050,
    boilingPoint: 1655,
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    atomicMass: 88.906,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d¹ 5s²",
    group: 3,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 4.47,
    meltingPoint: 1799,
    boilingPoint: 3609,
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomicMass: 91.224,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d² 5s²",
    group: 4,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 6.52,
    meltingPoint: 2128,
    boilingPoint: 4650,
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    atomicMass: 92.906,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d⁴ 5s¹",
    group: 5,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 8.57,
    meltingPoint: 2750,
    boilingPoint: 5017,
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomicMass: 95.95,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d⁵ 5s¹",
    group: 6,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 10.28,
    meltingPoint: 2896,
    boilingPoint: 4912,
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    atomicMass: 98,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d⁵ 5s²",
    group: 7,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 11.5,
    meltingPoint: 2473,
    boilingPoint: 4538,
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomicMass: 101.07,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d⁷ 5s¹",
    group: 8,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 12.37,
    meltingPoint: 2607,
    boilingPoint: 4423,
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomicMass: 102.91,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d⁸ 5s¹",
    group: 9,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 12.41,
    meltingPoint: 2237,
    boilingPoint: 3968,
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    atomicMass: 106.42,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d¹⁰",
    group: 10,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 12.023,
    meltingPoint: 1828.05,
    boilingPoint: 3236,
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    atomicMass: 107.87,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d¹⁰ 5s¹",
    group: 11,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 10.49,
    meltingPoint: 1234.93,
    boilingPoint: 2435,
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomicMass: 112.41,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d¹⁰ 5s²",
    group: 12,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 8.65,
    meltingPoint: 594.22,
    boilingPoint: 1038,
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    atomicMass: 114.82,
    category: "Post-transition Metal",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p¹",
    group: 13,
    period: 5,
    block: "p",
    phase: "Solid",
    density: 7.31,
    meltingPoint: 429.75,
    boilingPoint: 2345,
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    atomicMass: 118.71,
    category: "Post-transition Metal",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p²",
    group: 14,
    period: 5,
    block: "p",
    phase: "Solid",
    density: 7.287,
    meltingPoint: 505.08,
    boilingPoint: 2543,
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    atomicMass: 121.76,
    category: "Metalloid",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p³",
    group: 15,
    period: 5,
    block: "p",
    phase: "Solid",
    density: 6.697,
    meltingPoint: 903.78,
    boilingPoint: 1908,
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    atomicMass: 127.6,
    category: "Metalloid",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁴",
    group: 16,
    period: 5,
    block: "p",
    phase: "Solid",
    density: 6.24,
    meltingPoint: 722.66,
    boilingPoint: 1261,
  },
  {
    number: 53,
    symbol: "I",
    name: "Iodine",
    atomicMass: 126.9,
    category: "Halogen",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁵",
    group: 17,
    period: 5,
    block: "p",
    phase: "Solid",
    density: 4.94,
    meltingPoint: 386.85,
    boilingPoint: 457.4,
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    atomicMass: 131.29,
    category: "Noble Gas",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁶",
    group: 18,
    period: 5,
    block: "p",
    phase: "Gas",
    density: 0.005894,
    meltingPoint: 161.4,
    boilingPoint: 165.05,
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Caesium",
    atomicMass: 132.91,
    category: "Alkali Metal",
    electronConfig: "[Xe] 6s¹",
    group: 1,
    period: 6,
    block: "s",
    phase: "Solid",
    density: 1.93,
    meltingPoint: 301.7,
    boilingPoint: 944,
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    atomicMass: 137.33,
    category: "Alkaline Earth",
    electronConfig: "[Xe] 6s²",
    group: 2,
    period: 6,
    block: "s",
    phase: "Solid",
    density: 3.51,
    meltingPoint: 1000,
    boilingPoint: 2118,
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    atomicMass: 138.91,
    category: "Lanthanide",
    electronConfig: "[Xe] 5d¹ 6s²",
    group: 3,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 6.15,
    meltingPoint: 1193,
    boilingPoint: 3737,
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    atomicMass: 140.12,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹ 5d¹ 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 6.77,
    meltingPoint: 1071,
    boilingPoint: 3716,
    group: null,
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomicMass: 140.91,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f³ 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 6.77,
    meltingPoint: 1208,
    boilingPoint: 3793,
    group: null,
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomicMass: 144.24,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f⁴ 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 7.01,
    meltingPoint: 1297,
    boilingPoint: 3343,
    group: null,
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Promethium",
    atomicMass: 145,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f⁵ 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 7.26,
    meltingPoint: 1315,
    boilingPoint: 3273,
    group: null,
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    atomicMass: 150.36,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f⁶ 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 7.52,
    meltingPoint: 1345,
    boilingPoint: 2067,
    group: null,
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    atomicMass: 151.96,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f⁷ 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 5.244,
    meltingPoint: 1099,
    boilingPoint: 1802,
    group: null,
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomicMass: 157.25,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f⁷ 5d¹ 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 7.9,
    meltingPoint: 1585,
    boilingPoint: 3546,
    group: null,
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    atomicMass: 158.93,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f⁹ 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 8.23,
    meltingPoint: 1629,
    boilingPoint: 3503,
    group: null,
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomicMass: 162.5,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹⁰ 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 8.55,
    meltingPoint: 1644,
    boilingPoint: 2840,
    group: null,
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    atomicMass: 164.93,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹¹ 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 8.8,
    meltingPoint: 1747,
    boilingPoint: 2993,
    group: null,
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    atomicMass: 167.26,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹² 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 9.066,
    meltingPoint: 1802,
    boilingPoint: 3141,
    group: null,
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thulium",
    atomicMass: 168.93,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹³ 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 9.32,
    meltingPoint: 1818,
    boilingPoint: 2223,
    group: null,
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomicMass: 173.05,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹⁴ 6s²",
    period: 6,
    block: "f",
    phase: "Solid",
    density: 6.9,
    meltingPoint: 1097,
    boilingPoint: 1469,
    group: null,
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomicMass: 174.97,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹⁴ 5d¹ 6s²",
    group: 3,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 9.841,
    meltingPoint: 1925,
    boilingPoint: 3675,
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomicMass: 178.49,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d² 6s²",
    group: 4,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 13.31,
    meltingPoint: 2506,
    boilingPoint: 4876,
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomicMass: 180.95,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d³ 6s²",
    group: 5,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 16.69,
    meltingPoint: 3290,
    boilingPoint: 5731,
  },
  {
    number: 74,
    symbol: "W",
    name: "Tungsten",
    atomicMass: 183.84,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    group: 6,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 19.25,
    meltingPoint: 3695,
    boilingPoint: 5828,
  },
  {
    number: 75,
    symbol: "Re",
    name: "Rhenium",
    atomicMass: 186.21,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    group: 7,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 21.02,
    meltingPoint: 3459,
    boilingPoint: 5869,
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    atomicMass: 190.23,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    group: 8,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 22.59,
    meltingPoint: 3306,
    boilingPoint: 5285,
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    atomicMass: 192.22,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    group: 9,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 22.65,
    meltingPoint: 2719,
    boilingPoint: 4701,
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platinum",
    atomicMass: 195.08,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    group: 10,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 21.45,
    meltingPoint: 2041.4,
    boilingPoint: 4098,
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    atomicMass: 196.97,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    group: 11,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 19.3,
    meltingPoint: 1337.33,
    boilingPoint: 3129,
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    atomicMass: 200.59,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    group: 12,
    period: 6,
    block: "d",
    phase: "Liquid",
    density: 13.534,
    meltingPoint: 234.32,
    boilingPoint: 629.88,
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    atomicMass: 204.38,
    category: "Post-transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    group: 13,
    period: 6,
    block: "p",
    phase: "Solid",
    density: 11.85,
    meltingPoint: 577,
    boilingPoint: 1746,
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    atomicMass: 207.2,
    category: "Post-transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    group: 14,
    period: 6,
    block: "p",
    phase: "Solid",
    density: 11.34,
    meltingPoint: 600.61,
    boilingPoint: 2022,
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomicMass: 208.98,
    category: "Post-transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    group: 15,
    period: 6,
    block: "p",
    phase: "Solid",
    density: 9.78,
    meltingPoint: 544.7,
    boilingPoint: 1837,
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    atomicMass: 209,
    category: "Metalloid",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    group: 16,
    period: 6,
    block: "p",
    phase: "Solid",
    density: 9.32,
    meltingPoint: 527,
    boilingPoint: 1235,
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    atomicMass: 210,
    category: "Halogen",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    group: 17,
    period: 6,
    block: "p",
    phase: "Solid",
    density: 7,
    meltingPoint: 575,
    boilingPoint: 610,
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    atomicMass: 222,
    category: "Noble Gas",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    group: 18,
    period: 6,
    block: "p",
    phase: "Gas",
    density: 0.00973,
    meltingPoint: 202,
    boilingPoint: 211.3,
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    atomicMass: 223,
    category: "Alkali Metal",
    electronConfig: "[Rn] 7s¹",
    group: 1,
    period: 7,
    block: "s",
    phase: "Solid",
    density: 2.48,
    meltingPoint: 300,
    boilingPoint: 950,
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    atomicMass: 226,
    category: "Alkaline Earth",
    electronConfig: "[Rn] 7s²",
    group: 2,
    period: 7,
    block: "s",
    phase: "Solid",
    density: 5.5,
    meltingPoint: 973,
    boilingPoint: 2010,
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    atomicMass: 227,
    category: "Actinide",
    electronConfig: "[Rn] 6d¹ 7s²",
    group: 3,
    period: 7,
    block: "d",
    phase: "Solid",
    density: 10.07,
    meltingPoint: 1323,
    boilingPoint: 3473,
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    atomicMass: 232.04,
    category: "Actinide",
    electronConfig: "[Rn] 6d² 7s²",
    period: 7,
    block: "d",
    phase: "Solid",
    density: 11.7,
    meltingPoint: 2023,
    boilingPoint: 5061,
    group: null,
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomicMass: 231.04,
    category: "Actinide",
    electronConfig: "[Rn] 5f² 6d¹ 7s²",
    period: 7,
    block: "f",
    phase: "Solid",
    density: 15.37,
    meltingPoint: 1841,
    boilingPoint: 4300,
    group: null,
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    atomicMass: 238.03,
    category: "Actinide",
    electronConfig: "[Rn] 5f³ 6d¹ 7s²",
    period: 7,
    block: "f",
    phase: "Solid",
    density: 19.05,
    meltingPoint: 1405.3,
    boilingPoint: 4407,
    group: null,
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    atomicMass: 237,
    category: "Actinide",
    electronConfig: "[Rn] 5f⁴ 6d¹ 7s²",
    period: 7,
    block: "f",
    phase: "Solid",
    density: 20.45,
    meltingPoint: 912,
    boilingPoint: 4273,
    group: null,
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomicMass: 244,
    category: "Actinide",
    electronConfig: "[Rn] 5f⁶ 7s²",
    period: 7,
    block: "f",
    phase: "Solid",
    density: 19.816,
    meltingPoint: 913,
    boilingPoint: 3501,
    group: null,
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americium",
    atomicMass: 243,
    category: "Actinide",
    electronConfig: "[Rn] 5f⁷ 7s²",
    period: 7,
    block: "f",
    phase: "Solid",
    density: 13.69,
    meltingPoint: 1449,
    boilingPoint: 2880,
    group: null,
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curium",
    atomicMass: 247,
    category: "Actinide",
    electronConfig: "[Rn] 5f⁷ 6d¹ 7s²",
    period: 7,
    block: "f",
    phase: "Solid",
    density: 13.51,
    meltingPoint: 1613,
    boilingPoint: 3383,
    group: null,
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomicMass: 247,
    category: "Actinide",
    electronConfig: "[Rn] 5f⁹ 7s²",
    period: 7,
    block: "f",
    phase: "Solid",
    density: 14.78,
    meltingPoint: 1259,
    boilingPoint: 2900,
    group: null,
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californium",
    atomicMass: 251,
    category: "Actinide",
    electronConfig: "[Rn] 5f¹⁰ 7s²",
    period: 7,
    block: "f",
    phase: "Solid",
    density: 15.1,
    meltingPoint: 1173,
    boilingPoint: 1743,
    group: null,
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomicMass: 252,
    category: "Actinide",
    electronConfig: "[Rn] 5f¹¹ 7s²",
    period: 7,
    block: "f",
    phase: "Solid",
    density: 8.84,
    meltingPoint: 1133,
    boilingPoint: 1269,
    group: null,
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    atomicMass: 257,
    category: "Actinide",
    electronConfig: "[Rn] 5f¹² 7s²",
    period: 7,
    block: "f",
    phase: "Solid",
    density: 9.7,
    meltingPoint: 1800,
    boilingPoint: null,
    group: null,
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomicMass: 258,
    category: "Actinide",
    electronConfig: "[Rn] 5f¹³ 7s²",
    period: 7,
    block: "f",
    phase: "Solid",
    density: 10.3,
    meltingPoint: 1100,
    boilingPoint: null,
    group: null,
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    atomicMass: 259,
    category: "Actinide",
    electronConfig: "[Rn] 5f¹⁴ 7s²",
    period: 7,
    block: "f",
    phase: "Solid",
    density: 9.9,
    meltingPoint: 1100,
    boilingPoint: null,
    group: null,
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomicMass: 262,
    category: "Actinide",
    electronConfig: "[Rn] 5f¹⁴ 6d¹ 7s²",
    group: 3,
    period: 7,
    block: "d",
    phase: "Solid",
    density: null,
    meltingPoint: 1900,
    boilingPoint: null,
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomicMass: 267,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d² 7s²",
    group: 4,
    period: 7,
    block: "d",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    atomicMass: 268,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d³ 7s²",
    group: 5,
    period: 7,
    block: "d",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomicMass: 269,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    group: 6,
    period: 7,
    block: "d",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomicMass: 270,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    group: 7,
    period: 7,
    block: "d",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    atomicMass: 277,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    group: 8,
    period: 7,
    block: "d",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomicMass: 278,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    group: 9,
    period: 7,
    block: "d",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomicMass: 281,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s¹",
    group: 10,
    period: 7,
    block: "d",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomicMass: 282,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s¹",
    group: 11,
    period: 7,
    block: "d",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomicMass: 285,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    group: 12,
    period: 7,
    block: "d",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomicMass: 286,
    category: "Post-transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    group: 13,
    period: 7,
    block: "p",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomicMass: 289,
    category: "Post-transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    group: 14,
    period: 7,
    block: "p",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomicMass: 290,
    category: "Post-transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    group: 15,
    period: 7,
    block: "p",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomicMass: 293,
    category: "Post-transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    group: 16,
    period: 7,
    block: "p",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomicMass: 294,
    category: "Halogen",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    group: 17,
    period: 7,
    block: "p",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    atomicMass: 294,
    category: "Noble Gas",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    group: 18,
    period: 7,
    block: "p",
    phase: "Solid",
    density: null,
    meltingPoint: null,
    boilingPoint: null,
  },
];

const PeriodicTableExplorer = () => {
  const [selectedElement, setSelectedElement] = useState(null);
  const [filter, setFilter] = useState("All");

  // Filtered list based on category
  const filteredElements =
    filter === "All"
      ? periodicTable
      : periodicTable.filter((element) => element.category === filter);

  return (
    <div className="mx-auto p-6 bg-white shadow-lg rounded-lg">
      <h2 className="text-2xl font-semibold mb-6 text-center text-gray-800">
        Periodic Table Explorer
      </h2>

      {/* Filter Dropdown */}
      <div className="mb-4">
        <label className="font-medium text-secondary">
          Filter by Category:
        </label>
        <select
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          className="ml-2 p-2 border rounded-lg"
        >
          <option value="All">All</option>
          <option value="Nonmetal">Nonmetals</option>
          <option value="Noble Gas">Noble Gases</option>
          <option value="Alkali Metal">Alkali Metals</option>
          <option value="Alkaline Earth">Alkaline Earth Metals</option>
          <option value="Metalloid">Metalloids</option>
          <option value="Halogen">Halogens</option>
          <option value="Post-transition Metal">Post-transition Metals</option>
          <option value="Transition Metal">Transition Metals</option>
          <option value="Lanthanide">Lanthanides</option>
          <option value="Actinide">Actinides</option>
        </select>
      </div>

      {/* Grid Display of Elements */}
      <div className="flex flex-wrap gap-3 text-center">
        {filteredElements.map((element) => (
          <button
            key={element.number}
            className={`py-1.5 px-5 rounded-xl shadow-md transition duration-200 transform hover:scale-105`}
            onClick={() => setSelectedElement(element)}
          >
            <div className="text-xl font-bold text-secondary">
              {element.symbol}
            </div>
            <div className="text-sm text-primary">{element.number}</div>
          </button>
        ))}
      </div>

      {/* Selected Element Details */}
      {selectedElement && (
        <div className="mt-6 p-4 border rounded-lg bg-gray-50">
          <h3 className="text-lg font-semibold text-primary">
            {selectedElement.name} ({selectedElement.symbol})
          </h3>
          <div className="flex flex-wrap gap-1 text-primary mt-1">
            <p className="bg-white py-0.5 px-3 rounded-full shadow-sm">
              <strong className="text-secondary">Atomic Number:</strong>{" "}
              {selectedElement.number}
            </p>

            <p className="bg-white py-0.5 px-3 rounded-full shadow-sm">
              <strong className="text-secondary">Atomic Mass:</strong>{" "}
              {selectedElement.atomicMass}
            </p>

            <p className="bg-white py-0.5 px-3 rounded-full shadow-sm">
              <strong className="text-secondary">Category:</strong>{" "}
              {selectedElement.category}
            </p>

            <p className="bg-white py-0.5 px-3 rounded-full shadow-sm">
              <strong className="text-secondary">
                Electron Configuration:
              </strong>
              {selectedElement.electronConfig}
            </p>

            <p className="bg-white py-0.5 px-3 rounded-full shadow-sm">
              <strong className="text-secondary">Group:</strong>{" "}
              {selectedElement.group || "N/A"}
            </p>

            <p className="bg-white py-0.5 px-3 rounded-full shadow-sm">
              <strong className="text-secondary">Period:</strong>{" "}
              {selectedElement.period}
            </p>

            <p className="bg-white py-0.5 px-3 rounded-full shadow-sm">
              <strong className="text-secondary">Block:</strong>{" "}
              {selectedElement.block}
            </p>

            <p className="bg-white py-0.5 px-3 rounded-full shadow-sm">
              <strong className="text-secondary">Phase:</strong>{" "}
              {selectedElement.phase}
            </p>

            <p className="bg-white py-0.5 px-3 rounded-full shadow-sm">
              <strong className="text-secondary">Density:</strong>{" "}
              {selectedElement.density}
              {selectedElement.density ? " g/cm³" : " N/A"}
            </p>

            <p className="bg-white py-0.5 px-3 rounded-full shadow-sm">
              <strong className="text-secondary">Melting Point:</strong>{" "}
              {selectedElement.meltingPoint}
              {selectedElement.meltingPoint ? " K" : " N/A"}
            </p>

            <p className="bg-white py-0.5 px-3 rounded-full shadow-sm">
              <strong className="text-secondary">Boiling Point:</strong>{" "}
              {selectedElement.boilingPoint}
              {selectedElement.boilingPoint ? " K" : " N/A"}
            </p>
          </div>
        </div>
      )}
    </div>
  );
};

export default PeriodicTableExplorer;
