"use client";
import React, { useState } from "react";
import { FaSearch, FaSync, FaDownload, FaCopy } from "react-icons/fa";

// Updated Periodic Table Data (complete 118 elements)
const periodicTable = [
  {
    number: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: 1.00794,
    category: "Nonmetal",
    electronConfig: "1s¹",
    group: 1,
    period: 1,
    block: "s",
    phase: "Gas",
    density: 0.00008988,
    meltingPoint: 13.99,
    boilingPoint: 20.271,
    electronegativity: 2.20,
    ionizationEnergy: 1312.0,
  },
  {
    number: 2,
    symbol: "He",
    name: "Helium",
    atomicMass: 4.002602,
    category: "Noble Gas",
    electronConfig: "1s²",
    group: 18,
    period: 1,
    block: "s",
    phase: "Gas",
    density: 0.0001785,
    meltingPoint: 0.95,
    boilingPoint: 4.222,
    electronegativity: null,
    ionizationEnergy: 2372.3,
  },
  {
    number: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: 6.94,
    category: "Alkali Metal",
    electronConfig: "[He] 2s¹",
    group: 1,
    period: 2,
    block: "s",
    phase: "Solid",
    density: 0.534,
    meltingPoint: 453.65,
    boilingPoint: 1603,
    electronegativity: 0.98,
    ionizationEnergy: 520.2,
  },
  {
    number: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicMass: 9.0121831,
    category: "Alkaline Earth",
    electronConfig: "[He] 2s²",
    group: 2,
    period: 2,
    block: "s",
    phase: "Solid",
    density: 1.85,
    meltingPoint: 1560,
    boilingPoint: 2742,
    electronegativity: 1.57,
    ionizationEnergy: 899.5,
  },
  {
    number: 5,
    symbol: "B",
    name: "Boron",
    atomicMass: 10.81,
    category: "Metalloid",
    electronConfig: "[He] 2s² 2p¹",
    group: 13,
    period: 2,
    block: "p",
    phase: "Solid",
    density: 2.34,
    meltingPoint: 2349,
    boilingPoint: 4200,
    electronegativity: 2.04,
    ionizationEnergy: 800.6,
  },
  {
    number: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: 12.011,
    category: "Nonmetal",
    electronConfig: "[He] 2s² 2p²",
    group: 14,
    period: 2,
    block: "p",
    phase: "Solid",
    density: 2.267,
    meltingPoint: 3915,
    boilingPoint: null,
    electronegativity: 2.55,
    ionizationEnergy: 1086.5,
  },
  {
    number: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: 14.007,
    category: "Nonmetal",
    electronConfig: "[He] 2s² 2p³",
    group: 15,
    period: 2,
    block: "p",
    phase: "Gas",
    density: 0.0012506,
    meltingPoint: 63.15,
    boilingPoint: 77.355,
    electronegativity: 3.04,
    ionizationEnergy: 1402.3,
  },
  {
    number: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: 15.999,
    category: "Nonmetal",
    electronConfig: "[He] 2s² 2p⁴",
    group: 16,
    period: 2,
    block: "p",
    phase: "Gas",
    density: 0.001429,
    meltingPoint: 54.36,
    boilingPoint: 90.188,
    electronegativity: 3.44,
    ionizationEnergy: 1313.9,
  },
  {
    number: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: 18.998403163,
    category: "Halogen",
    electronConfig: "[He] 2s² 2p⁵",
    group: 17,
    period: 2,
    block: "p",
    phase: "Gas",
    density: 0.001696,
    meltingPoint: 53.48,
    boilingPoint: 85.03,
    electronegativity: 3.98,
    ionizationEnergy: 1681.0,
  },
  {
    number: 10,
    symbol: "Ne",
    name: "Neon",
    atomicMass: 20.1797,
    category: "Noble Gas",
    electronConfig: "[He] 2s² 2p⁶",
    group: 18,
    period: 2,
    block: "p",
    phase: "Gas",
    density: 0.0008999,
    meltingPoint: 24.56,
    boilingPoint: 27.104,
    electronegativity: null,
    ionizationEnergy: 2080.7,
  },
  {
    number: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: 22.98976928,
    category: "Alkali Metal",
    electronConfig: "[Ne] 3s¹",
    group: 1,
    period: 3,
    block: "s",
    phase: "Solid",
    density: 0.968,
    meltingPoint: 370.944,
    boilingPoint: 1156,
    electronegativity: 0.93,
    ionizationEnergy: 495.8,
  },
  {
    number: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: 24.305,
    category: "Alkaline Earth",
    electronConfig: "[Ne] 3s²",
    group: 2,
    period: 3,
    block: "s",
    phase: "Solid",
    density: 1.738,
    meltingPoint: 923,
    boilingPoint: 1363,
    electronegativity: 1.31,
    ionizationEnergy: 737.7,
  },
  {
    number: 13,
    symbol: "Al",
    name: "Aluminium",
    atomicMass: 26.9815385,
    category: "Post-transition Metal",
    electronConfig: "[Ne] 3s² 3p¹",
    group: 13,
    period: 3,
    block: "p",
    phase: "Solid",
    density: 2.7,
    meltingPoint: 933.47,
    boilingPoint: 2743,
    electronegativity: 1.61,
    ionizationEnergy: 577.5,
  },
  {
    number: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: 28.085,
    category: "Metalloid",
    electronConfig: "[Ne] 3s² 3p²",
    group: 14,
    period: 3,
    block: "p",
    phase: "Solid",
    density: 2.329,
    meltingPoint: 1687,
    boilingPoint: 3538,
    electronegativity: 1.90,
    ionizationEnergy: 786.5,
  },
  {
    number: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicMass: 30.973761998,
    category: "Nonmetal",
    electronConfig: "[Ne] 3s² 3p³",
    group: 15,
    period: 3,
    block: "p",
    phase: "Solid",
    density: 1.823,
    meltingPoint: 317.3,
    boilingPoint: 553.7,
    electronegativity: 2.19,
    ionizationEnergy: 1011.8,
  },
  {
    number: 16,
    symbol: "S",
    name: "Sulfur",
    atomicMass: 32.06,
    category: "Nonmetal",
    electronConfig: "[Ne] 3s² 3p⁴",
    group: 16,
    period: 3,
    block: "p",
    phase: "Solid",
    density: 2.07,
    meltingPoint: 388.36,
    boilingPoint: 717.8,
    electronegativity: 2.58,
    ionizationEnergy: 999.6,
  },
  {
    number: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: 35.45,
    category: "Halogen",
    electronConfig: "[Ne] 3s² 3p⁵",
    group: 17,
    period: 3,
    block: "p",
    phase: "Gas",
    density: 0.003214,
    meltingPoint: 171.6,
    boilingPoint: 239.11,
    electronegativity: 3.16,
    ionizationEnergy: 1251.2,
  },
  {
    number: 18,
    symbol: "Ar",
    name: "Argon",
    atomicMass: 39.948,
    category: "Noble Gas",
    electronConfig: "[Ne] 3s² 3p⁶",
    group: 18,
    period: 3,
    block: "p",
    phase: "Gas",
    density: 0.001784,
    meltingPoint: 83.81,
    boilingPoint: 87.302,
    electronegativity: null,
    ionizationEnergy: 1520.6,
  },
  {
    number: 19,
    symbol: "K",
    name: "Potassium",
    atomicMass: 39.0983,
    category: "Alkali Metal",
    electronConfig: "[Ar] 4s¹",
    group: 1,
    period: 4,
    block: "s",
    phase: "Solid",
    density: 0.862,
    meltingPoint: 336.7,
    boilingPoint: 1032,
    electronegativity: 0.82,
    ionizationEnergy: 418.8,
  },
  {
    number: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicMass: 40.078,
    category: "Alkaline Earth",
    electronConfig: "[Ar] 4s²",
    group: 2,
    period: 4,
    block: "s",
    phase: "Solid",
    density: 1.55,
    meltingPoint: 1115,
    boilingPoint: 1757,
    electronegativity: 1.00,
    ionizationEnergy: 589.8,
  },
  {
    number: 21,
    symbol: "Sc",
    name: "Scandium",
    atomicMass: 44.955908,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d¹ 4s²",
    group: 3,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 2.985,
    meltingPoint: 1814,
    boilingPoint: 3109,
    electronegativity: 1.36,
    ionizationEnergy: 633.1,
  },
  {
    number: 22,
    symbol: "Ti",
    name: "Titanium",
    atomicMass: 47.867,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d² 4s²",
    group: 4,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 4.506,
    meltingPoint: 1941,
    boilingPoint: 3560,
    electronegativity: 1.54,
    ionizationEnergy: 658.8,
  },
  {
    number: 23,
    symbol: "V",
    name: "Vanadium",
    atomicMass: 50.9415,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d³ 4s²",
    group: 5,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 6.11,
    meltingPoint: 2183,
    boilingPoint: 3680,
    electronegativity: 1.63,
    ionizationEnergy: 650.9,
  },
  {
    number: 24,
    symbol: "Cr",
    name: "Chromium",
    atomicMass: 51.9961,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d⁵ 4s¹",
    group: 6,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 7.15,
    meltingPoint: 2180,
    boilingPoint: 2944,
    electronegativity: 1.66,
    ionizationEnergy: 652.9,
  },
  {
    number: 25,
    symbol: "Mn",
    name: "Manganese",
    atomicMass: 54.938044,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d⁵ 4s²",
    group: 7,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 7.21,
    meltingPoint: 1519,
    boilingPoint: 2334,
    electronegativity: 1.55,
    ionizationEnergy: 717.3,
  },
  {
    number: 26,
    symbol: "Fe",
    name: "Iron",
    atomicMass: 55.845,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d⁶ 4s²",
    group: 8,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 7.874,
    meltingPoint: 1811,
    boilingPoint: 3134,
    electronegativity: 1.83,
    ionizationEnergy: 762.5,
  },
  {
    number: 27,
    symbol: "Co",
    name: "Cobalt",
    atomicMass: 58.933194,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d⁷ 4s²",
    group: 9,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 8.9,
    meltingPoint: 1768,
    boilingPoint: 3200,
    electronegativity: 1.88,
    ionizationEnergy: 760.4,
  },
  {
    number: 28,
    symbol: "Ni",
    name: "Nickel",
    atomicMass: 58.6934,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d⁸ 4s²",
    group: 10,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 8.908,
    meltingPoint: 1728,
    boilingPoint: 3003,
    electronegativity: 1.91,
    ionizationEnergy: 737.1,
  },
  {
    number: 29,
    symbol: "Cu",
    name: "Copper",
    atomicMass: 63.546,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d¹⁰ 4s¹",
    group: 11,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 8.96,
    meltingPoint: 1357.77,
    boilingPoint: 2835,
    electronegativity: 1.90,
    ionizationEnergy: 745.5,
  },
  {
    number: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicMass: 65.38,
    category: "Transition Metal",
    electronConfig: "[Ar] 3d¹⁰ 4s²",
    group: 12,
    period: 4,
    block: "d",
    phase: "Solid",
    density: 7.14,
    meltingPoint: 692.68,
    boilingPoint: 1180,
    electronegativity: 1.65,
    ionizationEnergy: 906.4,
  },
  {
    number: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicMass: 69.723,
    category: "Post-transition Metal",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p¹",
    group: 13,
    period: 4,
    block: "p",
    phase: "Solid",
    density: 5.91,
    meltingPoint: 302.9146,
    boilingPoint: 2477,
    electronegativity: 1.81,
    ionizationEnergy: 578.8,
  },
  {
    number: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicMass: 72.63,
    category: "Metalloid",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p²",
    group: 14,
    period: 4,
    block: "p",
    phase: "Solid",
    density: 5.323,
    meltingPoint: 1211.4,
    boilingPoint: 3106,
    electronegativity: 2.01,
    ionizationEnergy: 762.2,
  },
  {
    number: 33,
    symbol: "As",
    name: "Arsenic",
    atomicMass: 74.921595,
    category: "Metalloid",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p³",
    group: 15,
    period: 4,
    block: "p",
    phase: "Solid",
    density: 5.727,
    meltingPoint: 1090,
    boilingPoint: 876,
    electronegativity: 2.18,
    ionizationEnergy: 947.0,
  },
  {
    number: 34,
    symbol: "Se",
    name: "Selenium",
    atomicMass: 78.971,
    category: "Nonmetal",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁴",
    group: 16,
    period: 4,
    block: "p",
    phase: "Solid",
    density: 4.81,
    meltingPoint: 494,
    boilingPoint: 958,
    electronegativity: 2.55,
    ionizationEnergy: 941.0,
  },
  {
    number: 35,
    symbol: "Br",
    name: "Bromine",
    atomicMass: 79.904,
    category: "Halogen",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁵",
    group: 17,
    period: 4,
    block: "p",
    phase: "Liquid",
    density: 3.1028,
    meltingPoint: 265.8,
    boilingPoint: 332.0,
    electronegativity: 2.96,
    ionizationEnergy: 1139.9,
  },
  {
    number: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicMass: 83.798,
    category: "Noble Gas",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁶",
    group: 18,
    period: 4,
    block: "p",
    phase: "Gas",
    density: 0.003749,
    meltingPoint: 115.78,
    boilingPoint: 119.93,
    electronegativity: 3.00,
    ionizationEnergy: 1350.8,
  },
  {
    number: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomicMass: 85.4678,
    category: "Alkali Metal",
    electronConfig: "[Kr] 5s¹",
    group: 1,
    period: 5,
    block: "s",
    phase: "Solid",
    density: 1.532,
    meltingPoint: 312.45,
    boilingPoint: 961,
    electronegativity: 0.82,
    ionizationEnergy: 403.0,
  },
  {
    number: 38,
    symbol: "Sr",
    name: "Strontium",
    atomicMass: 87.62,
    category: "Alkaline Earth",
    electronConfig: "[Kr] 5s²",
    group: 2,
    period: 5,
    block: "s",
    phase: "Solid",
    density: 2.64,
    meltingPoint: 1050,
    boilingPoint: 1655,
    electronegativity: 0.95,
    ionizationEnergy: 549.5,
  },
  {
    number: 39,
    symbol: "Y",
    name: "Yttrium",
    atomicMass: 88.90584,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d¹ 5s²",
    group: 3,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 4.472,
    meltingPoint: 1799,
    boilingPoint: 3609,
    electronegativity: 1.22,
    ionizationEnergy: 600.0,
  },
  {
    number: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomicMass: 91.224,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d² 5s²",
    group: 4,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 6.52,
    meltingPoint: 2128,
    boilingPoint: 4650,
    electronegativity: 1.33,
    ionizationEnergy: 640.1,
  },
  {
    number: 41,
    symbol: "Nb",
    name: "Niobium",
    atomicMass: 92.90637,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d⁴ 5s¹",
    group: 5,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 8.57,
    meltingPoint: 2750,
    boilingPoint: 5017,
    electronegativity: 1.60,
    ionizationEnergy: 652.1,
  },
  {
    number: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomicMass: 95.95,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d⁵ 5s¹",
    group: 6,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 10.28,
    meltingPoint: 2896,
    boilingPoint: 4912,
    electronegativity: 2.16,
    ionizationEnergy: 684.3,
  },
  {
    number: 43,
    symbol: "Tc",
    name: "Technetium",
    atomicMass: 98,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d⁵ 5s²",
    group: 7,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 11.5,
    meltingPoint: 2430,
    boilingPoint: 4538,
    electronegativity: 1.90,
    ionizationEnergy: 702.0,
  },
  {
    number: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomicMass: 101.07,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d⁷ 5s¹",
    group: 8,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 12.45,
    meltingPoint: 2607,
    boilingPoint: 4423,
    electronegativity: 2.20,
    ionizationEnergy: 710.2,
  },
  {
    number: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomicMass: 102.90550,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d⁸ 5s¹",
    group: 9,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 12.41,
    meltingPoint: 2237,
    boilingPoint: 3968,
    electronegativity: 2.28,
    ionizationEnergy: 719.7,
  },
  {
    number: 46,
    symbol: "Pd",
    name: "Palladium",
    atomicMass: 106.42,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d¹⁰",
    group: 10,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 12.023,
    meltingPoint: 1828.05,
    boilingPoint: 3236,
    electronegativity: 2.20,
    ionizationEnergy: 804.4,
  },
  {
    number: 47,
    symbol: "Ag",
    name: "Silver",
    atomicMass: 107.8682,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d¹⁰ 5s¹",
    group: 11,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 10.49,
    meltingPoint: 1234.93,
    boilingPoint: 2435,
    electronegativity: 1.93,
    ionizationEnergy: 731.0,
  },
  {
    number: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomicMass: 112.414,
    category: "Transition Metal",
    electronConfig: "[Kr] 4d¹⁰ 5s²",
    group: 12,
    period: 5,
    block: "d",
    phase: "Solid",
    density: 8.65,
    meltingPoint: 594.22,
    boilingPoint: 1040,
    electronegativity: 1.69,
    ionizationEnergy: 867.8,
  },
  {
    number: 49,
    symbol: "In",
    name: "Indium",
    atomicMass: 114.818,
    category: "Post-transition Metal",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p¹",
    group: 13,
    period: 5,
    block: "p",
    phase: "Solid",
    density: 7.31,
    meltingPoint: 429.7485,
    boilingPoint: 2345,
    electronegativity: 1.78,
    ionizationEnergy: 558.3,
  },
  {
    number: 50,
    symbol: "Sn",
    name: "Tin",
    atomicMass: 118.710,
    category: "Post-transition Metal",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p²",
    group: 14,
    period: 5,
    block: "p",
    phase: "Solid",
    density: 7.287,
    meltingPoint: 505.08,
    boilingPoint: 2875,
    electronegativity: 1.96,
    ionizationEnergy: 708.6,
  },
  {
    number: 51,
    symbol: "Sb",
    name: "Antimony",
    atomicMass: 121.760,
    category: "Metalloid",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p³",
    group: 15,
    period: 5,
    block: "p",
    phase: "Solid",
    density: 6.697,
    meltingPoint: 903.78,
    boilingPoint: 1908,
    electronegativity: 2.05,
    ionizationEnergy: 834.0,
  },
  {
    number: 52,
    symbol: "Te",
    name: "Tellurium",
    atomicMass: 127.60,
    category: "Metalloid",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁴",
    group: 16,
    period: 5,
    block: "p",
    phase: "Solid",
    density: 6.24,
    meltingPoint: 722.66,
    boilingPoint: 1261,
    electronegativity: 2.10,
    ionizationEnergy: 869.3,
  },
  {
    number: 53,
    symbol: "I",
    name: "Iodine",
    atomicMass: 126.90447,
    category: "Halogen",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁵",
    group: 17,
    period: 5,
    block: "p",
    phase: "Solid",
    density: 4.933,
    meltingPoint: 386.85,
    boilingPoint: 457.4,
    electronegativity: 2.66,
    ionizationEnergy: 1008.4,
  },
  {
    number: 54,
    symbol: "Xe",
    name: "Xenon",
    atomicMass: 131.293,
    category: "Noble Gas",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁶",
    group: 18,
    period: 5,
    block: "p",
    phase: "Gas",
    density: 0.005894,
    meltingPoint: 161.4,
    boilingPoint: 165.051,
    electronegativity: 2.60,
    ionizationEnergy: 1170.4,
  },
  {
    number: 55,
    symbol: "Cs",
    name: "Caesium",
    atomicMass: 132.90545196,
    category: "Alkali Metal",
    electronConfig: "[Xe] 6s¹",
    group: 1,
    period: 6,
    block: "s",
    phase: "Solid",
    density: 1.93,
    meltingPoint: 301.7,
    boilingPoint: 944,
    electronegativity: 0.79,
    ionizationEnergy: 375.7,
  },
  {
    number: 56,
    symbol: "Ba",
    name: "Barium",
    atomicMass: 137.327,
    category: "Alkaline Earth",
    electronConfig: "[Xe] 6s²",
    group: 2,
    period: 6,
    block: "s",
    phase: "Solid",
    density: 3.51,
    meltingPoint: 1000,
    boilingPoint: 2118,
    electronegativity: 0.89,
    ionizationEnergy: 502.9,
  },
  {
    number: 57,
    symbol: "La",
    name: "Lanthanum",
    atomicMass: 138.90547,
    category: "Lanthanide",
    electronConfig: "[Xe] 5d¹ 6s²",
    group: 3,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 6.162,
    meltingPoint: 1193,
    boilingPoint: 3737,
    electronegativity: 1.10,
    ionizationEnergy: 538.1,
  },
  {
    number: 58,
    symbol: "Ce",
    name: "Cerium",
    atomicMass: 140.116,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹ 5d¹ 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 6.77,
    meltingPoint: 1068,
    boilingPoint: 3716,
    electronegativity: 1.12,
    ionizationEnergy: 534.4,
  },
  {
    number: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomicMass: 140.90766,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f³ 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 6.77,
    meltingPoint: 1208,
    boilingPoint: 3793,
    electronegativity: 1.13,
    ionizationEnergy: 527.0,
  },
  {
    number: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomicMass: 144.242,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f⁴ 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 7.01,
    meltingPoint: 1297,
    boilingPoint: 3347,
    electronegativity: 1.14,
    ionizationEnergy: 533.1,
  },
  {
    number: 61,
    symbol: "Pm",
    name: "Promethium",
    atomicMass: 145,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f⁵ 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 7.26,
    meltingPoint: 1315,
    boilingPoint: 3273,
    electronegativity: 1.13,
    ionizationEnergy: 540.0,
  },
  {
    number: 62,
    symbol: "Sm",
    name: "Samarium",
    atomicMass: 150.36,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f⁶ 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 7.52,
    meltingPoint: 1345,
    boilingPoint: 2067,
    electronegativity: 1.17,
    ionizationEnergy: 544.5,
  },
  {
    number: 63,
    symbol: "Eu",
    name: "Europium",
    atomicMass: 151.964,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f⁷ 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 5.244,
    meltingPoint: 1099,
    boilingPoint: 1802,
    electronegativity: 1.20,
    ionizationEnergy: 547.1,
  },
  {
    number: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomicMass: 157.25,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f⁷ 5d¹ 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 7.90,
    meltingPoint: 1585,
    boilingPoint: 3546,
    electronegativity: 1.20,
    ionizationEnergy: 593.4,
  },
  {
    number: 65,
    symbol: "Tb",
    name: "Terbium",
    atomicMass: 158.92535,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f⁹ 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 8.23,
    meltingPoint: 1629,
    boilingPoint: 3503,
    electronegativity: 1.20,
    ionizationEnergy: 565.8,
  },
  {
    number: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomicMass: 162.500,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹⁰ 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 8.55,
    meltingPoint: 1680,
    boilingPoint: 2840,
    electronegativity: 1.22,
    ionizationEnergy: 573.0,
  },
  {
    number: 67,
    symbol: "Ho",
    name: "Holmium",
    atomicMass: 164.93033,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹¹ 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 8.79,
    meltingPoint: 1734,
    boilingPoint: 2993,
    electronegativity: 1.23,
    ionizationEnergy: 581.0,
  },
  {
    number: 68,
    symbol: "Er",
    name: "Erbium",
    atomicMass: 167.259,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹² 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 9.066,
    meltingPoint: 1802,
    boilingPoint: 3141,
    electronegativity: 1.24,
    ionizationEnergy: 589.3,
  },
  {
    number: 69,
    symbol: "Tm",
    name: "Thulium",
    atomicMass: 168.93422,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹³ 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 9.32,
    meltingPoint: 1818,
    boilingPoint: 2223,
    electronegativity: 1.25,
    ionizationEnergy: 596.7,
  },
  {
    number: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomicMass: 173.045,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹⁴ 6s²",
    group: null,
    period: 6,
    block: "f",
    phase: "Solid",
    density: 6.90,
    meltingPoint: 1097,
    boilingPoint: 1469,
    electronegativity: 1.10,
    ionizationEnergy: 603.4,
  },
  {
    number: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomicMass: 174.9668,
    category: "Lanthanide",
    electronConfig: "[Xe] 4f¹⁴ 5d¹ 6s²",
    group: 3,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 9.841,
    meltingPoint: 1925,
    boilingPoint: 3675,
    electronegativity: 1.27,
    ionizationEnergy: 523.5,
  },
  {
    number: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomicMass: 178.49,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d² 6s²",
    group: 4,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 13.31,
    meltingPoint: 2506,
    boilingPoint: 4876,
    electronegativity: 1.30,
    ionizationEnergy: 658.5,
  },
  {
    number: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomicMass: 180.94788,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d³ 6s²",
    group: 5,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 16.69,
    meltingPoint: 3290,
    boilingPoint: 5731,
    electronegativity: 1.50,
    ionizationEnergy: 761.0,
  },
  {
    number: 74,
    symbol: "W",
    name: "Tungsten",
    atomicMass: 183.84,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    group: 6,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 19.25,
    meltingPoint: 3695,
    boilingPoint: 5828,
    electronegativity: 2.36,
    ionizationEnergy: 770.0,
  },
  {
    number: 75,
    symbol: "Re",
    name: "Rhenium",
    atomicMass: 186.207,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    group: 7,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 21.02,
    meltingPoint: 3459,
    boilingPoint: 5869,
    electronegativity: 1.90,
    ionizationEnergy: 760.0,
  },
  {
    number: 76,
    symbol: "Os",
    name: "Osmium",
    atomicMass: 190.23,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    group: 8,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 22.59,
    meltingPoint: 3306,
    boilingPoint: 5285,
    electronegativity: 2.20,
    ionizationEnergy: 840.0,
  },
  {
    number: 77,
    symbol: "Ir",
    name: "Iridium",
    atomicMass: 192.217,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    group: 9,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 22.56,
    meltingPoint: 2719,
    boilingPoint: 4701,
    electronegativity: 2.20,
    ionizationEnergy: 880.0,
  },
  {
    number: 78,
    symbol: "Pt",
    name: "Platinum",
    atomicMass: 195.084,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    group: 10,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 21.45,
    meltingPoint: 2041.4,
    boilingPoint: 4098,
    electronegativity: 2.28,
    ionizationEnergy: 870.0,
  },
  {
    number: 79,
    symbol: "Au",
    name: "Gold",
    atomicMass: 196.966569,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    group: 11,
    period: 6,
    block: "d",
    phase: "Solid",
    density: 19.32,
    meltingPoint: 1337.33,
    boilingPoint: 3129,
    electronegativity: 2.54,
    ionizationEnergy: 890.1,
  },
  {
    number: 80,
    symbol: "Hg",
    name: "Mercury",
    atomicMass: 200.592,
    category: "Transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    group: 12,
    period: 6,
    block: "d",
    phase: "Liquid",
    density: 13.534,
    meltingPoint: 234.3210,
    boilingPoint: 629.88,
    electronegativity: 2.00,
    ionizationEnergy: 1007.1,
  },
  {
    number: 81,
    symbol: "Tl",
    name: "Thallium",
    atomicMass: 204.38,
    category: "Post-transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    group: 13,
    period: 6,
    block: "p",
    phase: "Solid",
    density: 11.85,
    meltingPoint: 577,
    boilingPoint: 1746,
    electronegativity: 1.62,
    ionizationEnergy: 589.4,
  },
  {
    number: 82,
    symbol: "Pb",
    name: "Lead",
    atomicMass: 207.2,
    category: "Post-transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    group: 14,
    period: 6,
    block: "p",
    phase: "Solid",
    density: 11.34,
    meltingPoint: 600.61,
    boilingPoint: 2022,
    electronegativity: 2.33,
    ionizationEnergy: 715.6,
  },
  {
    number: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomicMass: 208.98040,
    category: "Post-transition Metal",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    group: 15,
    period: 6,
    block: "p",
    phase: "Solid",
    density: 9.78,
    meltingPoint: 544.7,
    boilingPoint: 1837,
    electronegativity: 2.02,
    ionizationEnergy: 703.0,
  },
  {
    number: 84,
    symbol: "Po",
    name: "Polonium",
    atomicMass: 209,
    category: "Metalloid",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    group: 16,
    period: 6,
    block: "p",
    phase: "Solid",
    density: 9.196,
    meltingPoint: 527,
    boilingPoint: 1235,
    electronegativity: 2.00,
    ionizationEnergy: 812.1,
  },
  {
    number: 85,
    symbol: "At",
    name: "Astatine",
    atomicMass: 210,
    category: "Halogen",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    group: 17,
    period: 6,
    block: "p",
    phase: "Solid",
    density: 6.35,
    meltingPoint: 575,
    boilingPoint: 610,
    electronegativity: 2.20,
    ionizationEnergy: 890.0,
  },
  {
    number: 86,
    symbol: "Rn",
    name: "Radon",
    atomicMass: 222,
    category: "Noble Gas",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    group: 18,
    period: 6,
    block: "p",
    phase: "Gas",
    density: 0.00973,
    meltingPoint: 202,
    boilingPoint: 211.5,
    electronegativity: 2.20,
    ionizationEnergy: 1037.0,
  },
  {
    number: 87,
    symbol: "Fr",
    name: "Francium",
    atomicMass: 223,
    category: "Alkali Metal",
    electronConfig: "[Rn] 7s¹",
    group: 1,
    period: 7,
    block: "s",
    phase: "Solid",
    density: 2.48,
    meltingPoint: 300,
    boilingPoint: 950,
    electronegativity: 0.70,
    ionizationEnergy: 380.0,
  },
  {
    number: 88,
    symbol: "Ra",
    name: "Radium",
    atomicMass: 226,
    category: "Alkaline Earth",
    electronConfig: "[Rn] 7s²",
    group: 2,
    period: 7,
    block: "s",
    phase: "Solid",
    density: 5.5,
    meltingPoint: 973,
    boilingPoint: 2010,
    electronegativity: 0.90,
    ionizationEnergy: 509.3,
  },
  {
    number: 89,
    symbol: "Ac",
    name: "Actinium",
    atomicMass: 227,
    category: "Actinide",
    electronConfig: "[Rn] 6d¹ 7s²",
    group: 3,
    period: 7,
    block: "d",
    phase: "Solid",
    density: 10.07,
    meltingPoint: 1323,
    boilingPoint: 3471,
    electronegativity: 1.10,
    ionizationEnergy: 499.0,
  },
  {
    number: 90,
    symbol: "Th",
    name: "Thorium",
    atomicMass: 232.0377,
    category: "Actinide",
    electronConfig: "[Rn] 6d² 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 11.72,
    meltingPoint: 2023,
    boilingPoint: 5061,
    electronegativity: 1.30,
    ionizationEnergy: 587.0,
  },
  {
    number: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomicMass: 231.03588,
    category: "Actinide",
    electronConfig: "[Rn] 5f² 6d¹ 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 15.37,
    meltingPoint: 1841,
    boilingPoint: 4300,
    electronegativity: 1.50,
    ionizationEnergy: 568.0,
  },
  {
    number: 92,
    symbol: "U",
    name: "Uranium",
    atomicMass: 238.02891,
    category: "Actinide",
    electronConfig: "[Rn] 5f³ 6d¹ 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 19.05,
    meltingPoint: 1405.3,
    boilingPoint: 4404,
    electronegativity: 1.38,
    ionizationEnergy: 597.6,
  },
  {
    number: 93,
    symbol: "Np",
    name: "Neptunium",
    atomicMass: 237,
    category: "Actinide",
    electronConfig: "[Rn] 5f⁴ 6d¹ 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 20.45,
    meltingPoint: 912,
    boilingPoint: 4273,
    electronegativity: 1.36,
    ionizationEnergy: 604.5,
  },
  {
    number: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomicMass: 244,
    category: "Actinide",
    electronConfig: "[Rn] 5f⁶ 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 19.816,
    meltingPoint: 912.5,
    boilingPoint: 3505,
    electronegativity: 1.28,
    ionizationEnergy: 584.7,
  },
  {
    number: 95,
    symbol: "Am",
    name: "Americium",
    atomicMass: 243,
    category: "Actinide",
    electronConfig: "[Rn] 5f⁷ 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 13.69,
    meltingPoint: 1449,
    boilingPoint: 2880,
    electronegativity: 1.30,
    ionizationEnergy: 578.0,
  },
  {
    number: 96,
    symbol: "Cm",
    name: "Curium",
    atomicMass: 247,
    category: "Actinide",
    electronConfig: "[Rn] 5f⁷ 6d¹ 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 13.51,
    meltingPoint: 1613,
    boilingPoint: 3383,
    electronegativity: 1.30,
    ionizationEnergy: 581.0,
  },
  {
    number: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomicMass: 247,
    category: "Actinide",
    electronConfig: "[Rn] 5f⁹ 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 14.78,
    meltingPoint: 1259,
    boilingPoint: 2900,
    electronegativity: 1.30,
    ionizationEnergy: 601.0,
  },
  {
    number: 98,
    symbol: "Cf",
    name: "Californium",
    atomicMass: 251,
    category: "Actinide",
    electronConfig: "[Rn] 5f¹⁰ 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 15.1,
    meltingPoint: 1173,
    boilingPoint: 1743,
    electronegativity: 1.30,
    ionizationEnergy: 608.0,
  },
  {
    number: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomicMass: 252,
    category: "Actinide",
    electronConfig: "[Rn] 5f¹¹ 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 8.84,
    meltingPoint: 1133,
    boilingPoint: 1269,
    electronegativity: 1.30,
    ionizationEnergy: 619.0,
  },
  {
    number: 100,
    symbol: "Fm",
    name: "Fermium",
    atomicMass: 257,
    category: "Actinide",
    electronConfig: "[Rn] 5f¹² 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 9.7,
    meltingPoint: 1800,
    boilingPoint: null,
    electronegativity: 1.30,
    ionizationEnergy: 627.0,
  },
  {
    number: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomicMass: 258,
    category: "Actinide",
    electronConfig: "[Rn] 5f¹³ 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 10.3,
    meltingPoint: 1100,
    boilingPoint: null,
    electronegativity: 1.30,
    ionizationEnergy: 635.0,
  },
  {
    number: 102,
    symbol: "No",
    name: "Nobelium",
    atomicMass: 259,
    category: "Actinide",
    electronConfig: "[Rn] 5f¹⁴ 7s²",
    group: null,
    period: 7,
    block: "f",
    phase: "Solid",
    density: 9.9,
    meltingPoint: 1100,
    boilingPoint: null,
    electronegativity: 1.30,
    ionizationEnergy: 642.0,
  },
  {
    number: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomicMass: 262,
    category: "Actinide",
    electronConfig: "[Rn] 5f¹⁴ 6d¹ 7s²",
    group: 3,
    period: 7,
    block: "d",
    phase: "Solid",
    density: 15.6,
    meltingPoint: 1900,
    boilingPoint: null,
    electronegativity: 1.30,
    ionizationEnergy: 470.0,
  },
  {
    number: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomicMass: 267,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d² 7s²",
    group: 4,
    period: 7,
    block: "d",
    phase: "Solid",
    density: 23.2,
    meltingPoint: 2400,
    boilingPoint: 5800,
    electronegativity: 1.30,
    ionizationEnergy: 580.0,
  },
  {
    number: 105,
    symbol: "Db",
    name: "Dubnium",
    atomicMass: 268,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d³ 7s²",
    group: 5,
    period: 7,
    block: "d",
    phase: "Solid",
    density: 29.3,
    meltingPoint: null,
    boilingPoint: null,
    electronegativity: null,
    ionizationEnergy: 665.0,
  },
  {
    number: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomicMass: 269,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    group: 6,
    period: 7,
    block: "d",
    phase: "Solid",
    density: 35.0,
    meltingPoint: null,
    boilingPoint: null,
    electronegativity: null,
    ionizationEnergy: 757.0,
  },
  {
    number: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomicMass: 270,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    group: 7,
    period: 7,
    block: "d",
    phase: "Solid",
    density: 37.1,
    meltingPoint: null,
    boilingPoint: null,
    electronegativity: null,
    ionizationEnergy: 733.0,
  },
  {
    number: 108,
    symbol: "Hs",
    name: "Hassium",
    atomicMass: 277,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    group: 8,
    period: 7,
    block: "d",
    phase: "Solid",
    density: 40.7,
    meltingPoint: null,
    boilingPoint: null,
    electronegativity: null,
    ionizationEnergy: 730.0,
  },
  {
    number: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomicMass: 278,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    group: 9,
    period: 7,
    block: "d",
    phase: "Solid",
    density: 37.4,
    meltingPoint: null,
    boilingPoint: null,
    electronegativity: null,
    ionizationEnergy: 825.0,
  },
  {
    number: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomicMass: 281,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁸ 7s²",
    group: 10,
    period: 7,
    block: "d",
    phase: "Solid",
    density: 34.8,
    meltingPoint: null,
    boilingPoint: null,
    electronegativity: null,
    ionizationEnergy: 960.0,
  },
  {
    number: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomicMass: 282,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d⁹ 7s²",
    group: 11,
    period: 7,
    block: "d",
    phase: "Solid",
    density: 28.7,
    meltingPoint: null,
    boilingPoint: null,
    electronegativity: null,
    ionizationEnergy: 1020.0,
  },
  {
    number: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomicMass: 285,
    category: "Transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    group: 12,
    period: 7,
    block: "d",
    phase: "Solid",
    density: 23.7,
    meltingPoint: null,
    boilingPoint: null,
    electronegativity: null,
    ionizationEnergy: 1155.0,
  },
  {
    number: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomicMass: 286,
    category: "Post-transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    group: 13,
    period: 7,
    block: "p",
    phase: "Solid",
    density: 16,
    meltingPoint: 700,
    boilingPoint: 1430,
    electronegativity: null,
    ionizationEnergy: 704.9,
  },
  {
    number: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomicMass: 289,
    category: "Post-transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    group: 14,
    period: 7,
    block: "p",
    phase: "Solid",
    density: 14,
    meltingPoint: 340,
    boilingPoint: 420,
    electronegativity: null,
    ionizationEnergy: 832.2,
  },
  {
    number: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomicMass: 290,
    category: "Post-transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    group: 15,
    period: 7,
    block: "p",
    phase: "Solid",
    density: 13.5,
    meltingPoint: 670,
    boilingPoint: 1400,
    electronegativity: null,
    ionizationEnergy: 538.3,
  },
  {
    number: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomicMass: 293,
    category: "Post-transition Metal",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    group: 16,
    period: 7,
    block: "p",
    phase: "Solid",
    density: 12.9,
    meltingPoint: 709,
    boilingPoint: 1085,
    electronegativity: null,
    ionizationEnergy: 723.6,
  },
  {
    number: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomicMass: 294,
    category: "Halogen",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    group: 17,
    period: 7,
    block: "p",
    phase: "Solid",
    density: 7.2,
    meltingPoint: 723,
    boilingPoint: 883,
    electronegativity: null,
    ionizationEnergy: 736.0,
  },
  {
    number: 118,
    symbol: "Og",
    name: "Oganesson",
    atomicMass: 294,
    category: "Noble Gas",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    group: 18,
    period: 7,
    block: "p",
    phase: "Solid",
    density: 7.2,
    meltingPoint: 325,
    boilingPoint: 450,
    electronegativity: null,
    ionizationEnergy: 839.4,
  },
];

// Category Colors
const categoryColors = {
  "Nonmetal": "bg-blue-100 text-blue-800",
  "Noble Gas": "bg-purple-100 text-purple-800",
  "Alkali Metal": "bg-red-100 text-red-800",
  "Alkaline Earth": "bg-orange-100 text-orange-800",
  "Metalloid": "bg-green-100 text-green-800",
  "Halogen": "bg-yellow-100 text-yellow-800",
  "Post-transition Metal": "bg-teal-100 text-teal-800",
  "Transition Metal": "bg-indigo-100 text-indigo-800",
  "Lanthanide": "bg-pink-100 text-pink-800",
  "Actinide": "bg-gray-100 text-gray-800",
};

const PeriodicTableExplorer = () => {
  const [selectedElement, setSelectedElement] = useState(null);
  const [filterCategory, setFilterCategory] = useState("All");
  const [searchTerm, setSearchTerm] = useState("");
  const [sortBy, setSortBy] = useState("number");
  const [sortOrder, setSortOrder] = useState("asc");
  const [tempUnit, setTempUnit] = useState("K");

  const filteredElements = periodicTable
    .filter((element) =>
      filterCategory === "All" ? true : element.category === filterCategory
    )
    .filter((element) =>
      `${element.name} ${element.symbol} ${element.number}`
        .toLowerCase()
        .includes(searchTerm.toLowerCase())
    )
    .sort((a, b) => {
      const valueA = a[sortBy] || 0;
      const valueB = b[sortBy] || 0;
      return sortOrder === "asc" ? valueA - valueB : valueB - valueA;
    });

  const convertTemp = (kelvin, unit) => {
    if (!kelvin) return "N/A";
    switch (unit) {
      case "C":
        return (kelvin - 273.15).toFixed(2);
      case "F":
        return ((kelvin - 273.15) * 9/5 + 32).toFixed(2);
      default:
        return kelvin.toFixed(2);
    }
  };

  const downloadJSON = () => {
    const data = selectedElement ? [selectedElement] : filteredElements;
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `periodic-table-${Date.now()}.json`;
    link.click();
  };

  const copyToClipboard = () => {
    if (!selectedElement) return;
    const text = Object.entries(selectedElement)
      .map(([key, value]) => `${key}: ${value}`)
      .join("\n");
    navigator.clipboard.writeText(text);
    alert("Element details copied to clipboard!");
  };

  const reset = () => {
    setFilterCategory("All");
    setSearchTerm("");
    setSortBy("number");
    setSortOrder("asc");
    setTempUnit("K");
    setSelectedElement(null);
  };
  return (
    <div className="min-h-screen  flex items-center justify-center ">
      <div className="w-full  bg-white rounded-xl shadow-lg p-6 sm:p-8">
        <h1 className="text-2xl sm:text-3xl font-bold text-center mb-6 text-gray-800">
          Periodic Table Explorer
        </h1>
  
        <div className="space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Filter by Category
              </label>
              <select
                value={filterCategory}
                onChange={(e) => setFilterCategory(e.target.value)}
                className="w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500"
              >
                <option value="All">All</option>
                {Object.keys(categoryColors).map((cat) => (
                  <option key={cat} value={cat}>{cat}</option>
                ))}
              </select>
            </div>
  
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Search
              </label>
              <div className="relative">
                <FaSearch className="absolute top-1/2 left-3 transform -translate-y-1/2 text-gray-400" />
                <input
                  type="text"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  placeholder="Search by name, symbol, or number"
                  className="w-full pl-10 p-2 border rounded-md focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </div>
  
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Sort By
              </label>
              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value)}
                className="w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500"
              >
                <option value="number">Atomic Number</option>
                <option value="atomicMass">Atomic Mass</option>
                <option value="name">Name</option>
                <option value="density">Density</option>
              </select>
              <select
                value={sortOrder}
                onChange={(e) => setSortOrder(e.target.value)}
                className="mt-1 w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500"
              >
                <option value="asc">Ascending</option>
                <option value="desc">Descending</option>
              </select>
            </div>
  
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Temperature Unit
              </label>
              <select
                value={tempUnit}
                onChange={(e) => setTempUnit(e.target.value)}
                className="w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500"
              >
                <option value="K">Kelvin (K)</option>
                <option value="C">Celsius (°C)</option>
                <option value="F">Fahrenheit (°F)</option>
              </select>
            </div>
          </div>
  
          <div className="flex flex-col sm:flex-row gap-4">
            <button
              onClick={downloadJSON}
              className="flex-1 py-2 px-4 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors flex items-center justify-center"
            >
              <FaDownload className="mr-2" /> Download
            </button>
            <button
              onClick={copyToClipboard}
              disabled={!selectedElement}
              className="flex-1 py-2 px-4 bg-gray-600 text-white rounded-md hover:bg-gray-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors flex items-center justify-center"
            >
              <FaCopy className="mr-2" /> Copy Details
            </button>
            <button
              onClick={reset}
              className="flex-1 py-2 px-4 bg-red-600 text-white rounded-md hover:bg-red-700 transition-colors flex items-center justify-center"
            >
              <FaSync className="mr-2" /> Reset
            </button>
          </div>
        </div>
  
        {/* Grid Display of Elements */}
        <div className="mt-6 grid grid-cols-2 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-10 gap-3">
          {filteredElements.map((element) => (
            <button
              key={element.number}
              onClick={() => setSelectedElement(element)}
              className={`p-2 rounded-lg shadow-md transition duration-200 transform hover:scale-105 ${
                categoryColors[element.category]
              } ${selectedElement?.number === element.number ? "ring-2 ring-blue-500" : ""}`}
            >
              <div className="text-lg font-bold">{element.symbol}</div>
              <div className="text-xs">{element.number}</div>
              <div className="text-xs truncate">{element.name}</div>
            </button>
          ))}
        </div>
  
        {/* Selected Element Details */}
        {selectedElement && (
          <div className="mt-6 p-4 border rounded-lg bg-gray-50">
            <h3 className="text-lg font-semibold text-gray-800">
              {selectedElement.name} ({selectedElement.symbol})
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-2">
              {[
                { label: "Atomic Number", value: selectedElement.number },
                { label: "Atomic Mass", value: selectedElement.atomicMass },
                { label: "Category", value: selectedElement.category },
                { label: "Electron Config", value: selectedElement.electronConfig },
                { label: "Group", value: selectedElement.group || "N/A" },
                { label: "Period", value: selectedElement.period },
                { label: "Block", value: selectedElement.block },
                { label: "Phase", value: selectedElement.phase },
                { label: "Density", value: selectedElement.density ? `${selectedElement.density} g/cm³` : "N/A" },
                { label: "Melting Point", value: `${convertTemp(selectedElement.meltingPoint, tempUnit)} ${tempUnit}` },
                { label: "Boiling Point", value: `${convertTemp(selectedElement.boilingPoint, tempUnit)} ${tempUnit}` },
                { label: "Electronegativity", value: selectedElement.electronegativity || "N/A" },
                { label: "Ionization Energy", value: selectedElement.ionizationEnergy ? `${selectedElement.ionizationEnergy} kJ/mol` : "N/A" },
              ].map(({ label, value }) => (
                <div key={label} className="bg-white py-1 px-3 rounded-full shadow-sm">
                  <strong className="text-gray-700">{label}:</strong> {value}
                </div>
              ))}
            </div>
          </div>
        )}
  
        {/* Features */}
        <div className="mt-6 p-4 bg-blue-50 rounded-lg border border-blue-200">
          <h3 className="font-semibold text-blue-700 mb-2">Features</h3>
          <ul className="list-disc list-inside text-blue-600 text-sm space-y-1">
            <li>Filter by category with color-coded elements</li>
            <li>Search by name, symbol, or atomic number</li>
            <li>Sort by number, mass, name, or density</li>
            <li>Temperature unit conversion (K, °C, °F)</li>
            <li>Download as JSON or copy details to clipboard</li>
          </ul>
        </div>
      </div>
    </div>
  );}

  export default PeriodicTableExplorer