import React from "react";
import {
  MdCheckCircle,
  MdTextFields,
  MdSwapHoriz,
  MdAutorenew,
  MdCode,
  MdImage,
  MdPictureAsPdf,
  MdStraighten,
  MdAccessTime,
  MdTransform,
  MdBuild,
  MdTrendingUp,
  MdSecurity,
  MdSmartToy,
  MdCalculate,
  MdPalette,
  MdAttachMoney,
  MdShare,
  MdWbSunny,
  MdScience,
  MdOutlineSpellcheck,
  MdOutlinePlagiarism,
  MdFormatQuote,
  MdOutlineTextFormat,
  MdOutlineFindReplace,
  MdOutlineCreate,
  MdOutlineEdit,
  MdOutlineSubtitles,
  MdOutlineTitle,
  MdOutlineWrapText,
  MdOutlineAutorenew,
  MdDns,
  MdHttp,
  MdOutlineNumbers,
} from "react-icons/md";
import { LuScanBarcode } from "react-icons/lu";
import WordCharacterCounter from "./seoData/WordCharacterCounter";

const ToolList = [
  {
    category: "Text Tools",
    slug: "text-tools",
    desc: "Text formatting and conversion tools",
    icon: <MdTextFields />,
    tools: [
      {
        name: "Word and Character Counter",
        slug: "word-character-counter",
        icon: <MdOutlineNumbers />,
        desc: "Analyze your text effortlessly with real-time word, character, sentence, and readability statistics.",
        code: "WordCharacterCounter",
        seo: WordCharacterCounter,
      },
      {
        name: "Find and Replace",
        slug: "find-replace",
        icon: <MdOutlineFindReplace />,
        desc: "Easily find and replace text within your content.",
        code: "findReplaceTool",
      },
      {
        name: "Text Case Converter",
        slug: "text-case-converter",
        icon: <MdOutlineTextFormat />,
        desc: "Convert text to uppercase, lowercase, title case, and more.",
        code: "textCaseConverter",
      },
      {
        name: "Text to Speech",
        slug: "text-to-speech",
        icon: <MdOutlineSubtitles />,
        desc: "Convert written text into natural-sounding speech.",
        code: "textToSpeechTool",
      },
      {
        name: "Text Editor",
        slug: "text-editor",
        icon: <MdOutlineEdit />,
        desc: "A simple and powerful text editor for writing and formatting.",
        code: "textEditorTool",
      },
      {
        name: "Text Beautifier",
        slug: "text-beautifier",
        icon: <MdOutlineWrapText />,
        desc: "Enhance and beautify text formatting instantly.",
        code: "textBeautifierTool",
      },
      {
        name: "Spell Checker",
        slug: "spell-checker",
        icon: <MdOutlineSpellcheck />,
        desc: "Check and correct spelling mistakes in your text.",
        code: "spellCheckerTool",
      },
      {
        name: "Grammar Checker",
        slug: "grammar-checker",
        icon: <MdOutlineSpellcheck />,
        desc: "Analyze and correct grammar errors in your writing.",
        code: "grammarCheckerTool",
      },
      {
        name: "Plagiarism Checker",
        slug: "plagiarism-checker",
        icon: <MdOutlinePlagiarism />,
        desc: "Detect and prevent plagiarism in your text.",
        code: "plagiarismCheckerTool",
      },
      {
        name: "Quote Validator",
        slug: "quote-validator",
        icon: <MdFormatQuote />,
        desc: "Verify and validate quotes for authenticity.",
        code: "quoteValidatorTool",
      },
      {
        name: "Text Duplicator Checker",
        slug: "text-duplicator-checker",
        icon: <MdOutlineTextFormat />,
        desc: "Identify duplicate text within your content.",
        code: "textDuplicatorCheckerTool",
      },
    ],
  },
  {
    category: "Generator Tools",
    slug: "generator-tools",
    desc: "Tools for generating text, codes, and more",
    icon: <MdAutorenew />,
    tools: [
      {
        name: "UUID Generator",
        slug: "uuid-generator",
        icon: <MdAutorenew />,
        desc: "Generate unique UUIDs for identifiers and security purposes.",
        code: "uuidGeneratorTool",
      },
      {
        name: "Barcode Generator",
        slug: "barcode-generator",
        icon: <LuScanBarcode />,
        desc: "Create barcodes for products, tracking, and inventory management.",
        code: "barcodeGeneratorTool",
      },
      {
        name: "QR Code Generator",
        slug: "qr-code-generator",
        icon: <MdBuild />,
        desc: "Generate QR codes for links, contact details, and more.",
        code: "qrCodeGeneratorTool",
      },
      {
        name: "Lorem Ipsum Generator",
        slug: "lorem-ipsum-generator",
        icon: <MdAutorenew />,
        desc: "Generate placeholder text for designs and mockups.",
        code: "loremIpsumGeneratorTool",
      },
      {
        name: "Random Number Generator",
        slug: "random-number-generator",
        icon: <MdBuild />,
        desc: "Generate random numbers within a given range.",
        code: "randomNumberGeneratorTool",
      },
      {
        name: "Hash Generator",
        slug: "hash-generator",
        icon: <MdSecurity />,
        desc: "Generate secure hash values using various algorithms.",
        code: "hashGeneratorTool",
      },
      {
        name: "Random Password Generator",
        slug: "password-generator",
        icon: <MdSecurity />,
        desc: "Create strong and secure passwords instantly.",
        code: "passwordGeneratorTool",
      },
    ],
  },
  {
    category: "Developer Tools",
    slug: "developer-tools",
    desc: "Essential tools for developers",
    icon: <MdCode />,
    tools: [
      {
        name: "JSON Formatter",
        slug: "json-formatter",
        icon: <MdCode />,
        desc: "Format and beautify JSON data for better readability.",
        code: "jsonFormatterTool",
      },
      {
        name: "Regex Tester",
        slug: "regex-tester",
        icon: <MdCode />,
        desc: "Test and debug regular expressions interactively.",
        code: "regexTesterTool",
      },
      {
        name: "Code Minifier",
        slug: "code-minifier",
        icon: <MdBuild />,
        desc: "Minify JavaScript, CSS, and HTML code for better performance.",
        code: "codeMinifierTool",
      },
      {
        name: "Markdown Previewer",
        slug: "markdown-previewer",
        icon: <MdCode />,
        desc: "Preview and render Markdown files in real time.",
        code: "markdownPreviewerTool",
      },
    ],
  },
  {
    category: "Image Tools",
    slug: "image-tools",
    desc: "Image editing and conversion tools",
    icon: <MdImage />,
    tools: [
      {
        name: "Image Resizer",
        slug: "image-resizer",
        icon: <MdStraighten />,
        desc: "Resize images to custom dimensions while maintaining quality.",
        code: "imageResizerTool",
      },
      {
        name: "Image Converter",
        slug: "image-converter",
        icon: <MdTransform />,
        desc: "Convert images between different formats such as JPG, PNG, and WebP.",
        code: "imageConverterTool",
      },
      {
        name: "Image Compressor",
        slug: "image-compressor",
        icon: <MdImage />,
        desc: "Compress images to reduce file size without losing quality.",
        code: "imageCompressorTool",
      },
      {
        name: "Image Cropper",
        slug: "image-cropper",
        icon: <MdImage />,
        desc: "Crop images to specific dimensions or aspect ratios.",
        code: "imageCropperTool",
      },
      {
        name: "Image Enhancer",
        slug: "image-enhancer",
        icon: <MdImage />,
        desc: "Enhance image quality with AI-powered adjustments.",
        code: "imageEnhancerTool",
      },
    ],
  },
  {
    category: "PDF Tools",
    slug: "pdf-tools",
    desc: "Tools for managing and converting PDFs",
    icon: <MdPictureAsPdf />,
    tools: [
      {
        name: "PDF to Word",
        slug: "pdf-to-word",
        icon: <MdOutlineCreate />,
        desc: "Convert PDF files into editable Word documents.",
        code: "pdfToWordTool",
      },
      {
        name: "PDF to Image",
        slug: "pdf-to-image",
        icon: <MdPictureAsPdf />,
        desc: "Convert PDF pages into high-quality images.",
        code: "pdfToImageTool",
      },
      {
        name: "Merge PDFs",
        slug: "merge-pdfs",
        icon: <MdPictureAsPdf />,
        desc: "Combine multiple PDF files into a single document.",
        code: "mergePdfsTool",
      },
      {
        name: "Split PDF",
        slug: "split-pdf",
        icon: <MdPictureAsPdf />,
        desc: "Extract pages or split large PDFs into smaller files.",
        code: "splitPdfTool",
      },
      {
        name: "Compress PDF",
        slug: "compress-pdf",
        icon: <MdPictureAsPdf />,
        desc: "Reduce the file size of PDFs without losing quality.",
        code: "compressPdfTool",
      },
    ],
  },
  {
    category: "Unit Converter",
    slug: "unit-converter-tools",
    desc: "Convert different measurement units",
    icon: <MdStraighten />,
    tools: [
      {
        name: "Length Converter",
        slug: "length-converter",
        icon: <MdStraighten />,
        desc: "Convert length measurements between different units such as meters, feet, and inches.",
        code: "lengthConverterTool",
      },
      {
        name: "Weight Converter",
        slug: "weight-converter",
        icon: <MdStraighten />,
        desc: "Easily convert weight units like kilograms, pounds, and grams.",
        code: "weightConverterTool",
      },
      {
        name: "Temperature Converter",
        slug: "temperature-converter",
        icon: <MdStraighten />,
        desc: "Convert temperatures between Celsius, Fahrenheit, and Kelvin.",
        code: "temperatureConverterTool",
      },
      {
        name: "Volume Converter",
        slug: "volume-converter",
        icon: <MdStraighten />,
        desc: "Convert volume units such as liters, milliliters, and gallons.",
        code: "volumeConverterTool",
      },
      {
        name: "Speed Converter",
        slug: "speed-converter",
        icon: <MdStraighten />,
        desc: "Convert speed units like kilometers per hour, miles per hour, and meters per second.",
        code: "speedConverterTool",
      },
    ],
  },
  {
    category: "Time Converter",
    slug: "time-converter-tools",
    desc: "Convert time formats and zones",
    icon: <MdAccessTime />,
    tools: [
      {
        name: "Time Zone Converter",
        slug: "time-zone-converter",
        icon: <MdAccessTime />,
        desc: "Convert time between different time zones worldwide.",
        code: "timeZoneConverterTool",
      },
      {
        name: "Epoch Time Converter",
        slug: "epoch-time-converter",
        icon: <MdAccessTime />,
        desc: "Convert Unix epoch timestamps to human-readable dates and vice versa.",
        code: "epochTimeConverterTool",
      },
      {
        name: "Date to Timestamp",
        slug: "date-to-timestamp",
        icon: <MdAccessTime />,
        desc: "Generate a timestamp from a given date and time.",
        code: "dateToTimestampTool",
      },
      {
        name: "Stopwatch",
        slug: "stopwatch",
        icon: <MdAccessTime />,
        desc: "A simple online stopwatch to track time accurately.",
        code: "stopwatchTool",
      },
      {
        name: "Countdown Timer",
        slug: "countdown-timer",
        icon: <MdAccessTime />,
        desc: "Set a countdown timer for any duration with alerts.",
        code: "countdownTimerTool",
      },
    ],
  },
  {
    category: "Data Converter",
    slug: "data-converter-tools",
    desc: "Convert and manipulate data formats",
    icon: <MdTransform />,
    tools: [
      {
        name: "CSV to JSON",
        slug: "csv-to-json",
        icon: <MdTransform />,
        desc: "Convert CSV data to JSON format easily.",
        code: "csvToJsonTool",
      },
      {
        name: "JSON to XML",
        slug: "json-to-xml",
        icon: <MdTransform />,
        desc: "Convert JSON data to XML format for seamless integration.",
        code: "jsonToXmlTool",
      },
      {
        name: "YAML to JSON Converter",
        slug: "yaml-to-json",
        icon: <MdTransform />,
        desc: "Convert YAML data to JSON format effortlessly.",
        code: "yamlToJsonTool",
      },
      {
        name: "Base64 Encoder",
        slug: "base64-encoder",
        icon: <MdSecurity />,
        desc: "Encode text or files to Base64 format.",
        code: "base64EncoderTool",
      },
      {
        name: "Base64 Decoder",
        slug: "base64-decoder",
        icon: <MdTransform />,
        desc: "Decode Base64-encoded text or files back to their original form.",
        code: "base64DecoderTool",
      },
      {
        name: "URL Encoder",
        slug: "url-encoder",
        icon: <MdTransform />,
        desc: "Encode special characters in URLs to make them safe for web use.",
        code: "urlEncoderTool",
      },
      {
        name: "URL Decoder",
        slug: "url-decoder",
        icon: <MdTransform />,
        desc: "Decode encoded URLs back to their original readable format.",
        code: "urlDecoderTool",
      },
    ],
  },
  {
    category: "Science Tools",
    slug: "science-tools",
    desc: "Tools for scientific calculations and simulations",
    icon: <MdScience />,
    tools: [
      {
        name: "Molecular Weight Calculator",
        slug: "molecular-weight-calculator",
        icon: <MdScience />,
        desc: "Calculate the molecular weight of chemical compounds based on their molecular formulas.",
        code: "molecularWeightCalculatorTool",
      },
      {
        name: "Physics Unit Converter",
        slug: "physics-unit-converter",
        icon: <MdScience />,
        desc: "Convert between different physics units for length, mass, energy, and more.",
        code: "physicsUnitConverterTool",
      },
      {
        name: "Chemical Equation Balancer",
        slug: "chemical-equation-balancer",
        icon: <MdScience />,
        desc: "Balance chemical equations automatically for accurate reactions.",
        code: "chemicalEquationBalancerTool",
      },
      {
        name: "Astronomical Unit Converter",
        slug: "astronomical-unit-converter",
        icon: <MdScience />,
        desc: "Convert astronomical units such as light-years, parsecs, and AU.",
        code: "astronomicalUnitConverterTool",
      },
      {
        name: "Periodic Table Explorer",
        slug: "periodic-table-explorer",
        icon: <MdScience />,
        desc: "Explore detailed information about elements in the periodic table.",
        code: "periodicTableExplorerTool",
      },
    ],
  },
  {
    category: "SEO Tools",
    slug: "seo-tools",
    desc: "Tools for search engine optimization",
    icon: <MdTrendingUp />,
    tools: [
      {
        name: "Keyword Research Tool",
        slug: "keyword-research-tool",
        icon: <MdTrendingUp />,
        desc: "Discover high-performing keywords for SEO and digital marketing.",
        code: "keywordResearchTool",
      },
      {
        name: "Backlink Checker",
        slug: "backlink-checker",
        icon: <MdTrendingUp />,
        desc: "Analyze backlinks to your website and track link-building efforts.",
        code: "backlinkCheckerTool",
      },
      {
        name: "Meta Tag Analyzer",
        slug: "meta-tag-analyzer",
        icon: <MdTrendingUp />,
        desc: "Analyze meta tags for SEO optimization and better search rankings.",
        code: "metaTagAnalyzerTool",
      },
      {
        name: "Page Speed Checker",
        slug: "page-speed-checker",
        icon: <MdTrendingUp />,
        desc: "Measure website loading speed and performance metrics.",
        code: "pageSpeedCheckerTool",
      },
      {
        name: "Domain Authority Checker",
        slug: "domain-authority-checker",
        icon: <MdTrendingUp />,
        desc: "Check the domain authority (DA) and page authority (PA) of any website.",
        code: "domainAuthorityCheckerTool",
      },
    ],
  },
  {
    category: "Security Tools",
    slug: "security-tools",
    desc: "Tools for security and encryption",
    icon: <MdSecurity />,
    tools: [
      {
        name: "Password Strength Checker",
        slug: "password-strength-checker",
        icon: <MdSecurity />,
        desc: "Evaluate the strength of your password and get security recommendations.",
        code: "passwordStrengthChecker",
      },
      {
        name: "SSL Checker",
        slug: "ssl-checker",
        icon: <MdSecurity />,
        desc: "Verify the validity and expiration of SSL certificates on websites.",
        code: "sslChecker",
      },
      {
        name: "IP Lookup",
        slug: "ip-lookup",
        icon: <MdSecurity />,
        desc: "Find geographical and network details associated with an IP address.",
        code: "ipLookup",
      },
      {
        name: "DNS Lookup",
        slug: "dns-lookup",
        icon: <MdDns />,
        desc: "Retrieve DNS records, including A, MX, CNAME, and TXT records.",
        code: "dnsLookup",
      },
      {
        name: "Email Validator",
        slug: "email-validator",
        icon: <MdSecurity />,
        desc: "Check if an email address is valid, properly formatted, and exists.",
        code: "emailValidator",
      },
      {
        name: "HTTP Header Checker",
        slug: "http-header-checker",
        icon: <MdHttp />,
        desc: "Analyze HTTP headers for security, caching, and redirection details.",
        code: "httpHeaderChecker",
      },
    ],
  },
  {
    category: "AI Tools",
    slug: "ai-tools",
    desc: "AI-powered tools",
    icon: <MdSmartToy />,
    tools: [
      {
        name: "AI Text Generator",
        slug: "ai-text-generator",
        icon: <MdSmartToy />,
        desc: "Generate AI-powered text for blogs, articles, and creative writing.",
        code: "aiTextGenerator",
      },
      {
        name: "AI Image Generator",
        slug: "ai-image-generator",
        icon: <MdPalette />,
        desc: "Generate AI-based images from text prompts using deep learning.",
        code: "aiImageGenerator",
      },
      {
        name: "AI Code Generator",
        slug: "ai-code-generator",
        icon: <MdCode />,
        desc: "Generate code snippets and full programs using AI assistance.",
        code: "aiCodeGenerator",
      },
      {
        name: "AI Summary Generator",
        slug: "ai-summary-generator",
        icon: <MdOutlineTitle />,
        desc: "Summarize lengthy articles, documents, or research papers with AI.",
        code: "aiSummaryGenerator",
      },
      {
        name: "AI Story Writer",
        slug: "ai-story-writer",
        icon: <MdOutlineCreate />,
        desc: "Create AI-generated short stories, novels, and creative content.",
        code: "aiStoryWriter",
      },
    ],
  },
  {
    category: "Math Tools",
    slug: "math-tools",
    desc: "Tools for calculations and equations",
    icon: <MdCalculate />,
    tools: [
      {
        name: "Scientific Calculator",
        slug: "scientific-calculator",
        icon: <MdCalculate />,
        desc: "Perform advanced mathematical calculations with a scientific calculator.",
        code: "scientificCalculator",
      },
      {
        name: "Equation Solver",
        slug: "equation-solver",
        icon: <MdCalculate />,
        desc: "Solve linear and quadratic equations instantly.",
        code: "equationSolver",
      },
      {
        name: "Factorial Calculator",
        slug: "factorial-calculator",
        icon: <MdCalculate />,
        desc: "Calculate the factorial of any number easily.",
        code: "factorialCalculator",
      },
      {
        name: "Matrix Calculator",
        slug: "matrix-calculator",
        icon: <MdCalculate />,
        desc: "Perform matrix operations like addition, multiplication, and inverses.",
        code: "matrixCalculator",
      },
      {
        name: "Percentage Calculator",
        slug: "percentage-calculator",
        icon: <MdCalculate />,
        desc: "Easily compute percentages for discounts, taxes, and profit margins.",
        code: "percentageCalculator",
      },
    ],
  },
  {
    category: "Color Tools",
    slug: "color-tools",
    desc: "Pick and convert colors",
    icon: <MdPalette />,
    tools: [
      {
        name: "Color Picker",
        slug: "color-picker",
        icon: <MdPalette />,
        desc: "Pick and preview colors with HEX, RGB, and HSL values.",
        code: "colorPicker",
      },
      {
        name: "Hex to RGB Converter",
        slug: "hex-to-rgb",
        icon: <MdPalette />,
        desc: "Convert HEX color codes to RGB and vice versa.",
        code: "hexToRgb",
      },
      {
        name: "Color Gradient Generator",
        slug: "color-gradient-generator",
        icon: <MdPalette />,
        desc: "Create beautiful color gradients with CSS code output.",
        code: "gradientGenerator",
      },
      {
        name: "Contrast Checker",
        slug: "contrast-checker",
        icon: <MdPalette />,
        desc: "Check color contrast for accessibility and readability compliance.",
        code: "contrastChecker",
      },
      {
        name: "Palette Generator",
        slug: "palette-generator",
        icon: <MdPalette />,
        desc: "Generate harmonious color palettes for design projects.",
        code: "paletteGenerator",
      },
    ],
  },
  {
    category: "Finance Tools",
    slug: "finance-tools",
    desc: "Financial calculators and converters",
    icon: <MdAttachMoney />,
    tools: [
      {
        name: "Currency Converter",
        slug: "currency-converter",
        icon: <MdAttachMoney />,
        desc: "Convert currencies with real-time exchange rates.",
        code: "currencyConverter",
      },
      {
        name: "Loan Calculator",
        slug: "loan-calculator",
        icon: <MdAttachMoney />,
        desc: "Calculate monthly payments and total interest for loans.",
        code: "loanCalculator",
      },
      {
        name: "Tax Calculator",
        slug: "tax-calculator",
        icon: <MdAttachMoney />,
        desc: "Compute taxes based on income and deductions.",
        code: "taxCalculator",
      },
      {
        name: "Investment Calculator",
        slug: "investment-calculator",
        icon: <MdAttachMoney />,
        desc: "Project potential investment growth over time.",
        code: "investmentCalculator",
      },
      {
        name: "Retirement Savings Calculator",
        slug: "retirement-savings-calculator",
        icon: <MdAttachMoney />,
        desc: "Plan your retirement savings and estimate future value.",
        code: "retirementCalculator",
      },
    ],
  },
  {
    category: "Social Media Tools",
    slug: "social-media-tools",
    desc: "Tools for social media management",
    icon: <MdShare />,
    tools: [
      {
        name: "Hashtag Generator",
        slug: "hashtag-generator",
        icon: <MdShare />,
        desc: "Generate trending and relevant hashtags for social media.",
        code: "hashtagGenerator",
      },
      {
        name: "Username Checker",
        slug: "username-checker",
        icon: <MdShare />,
        desc: "Check username availability across multiple platforms.",
        code: "usernameChecker",
      },
    ],
  },
  {
    category: "Weather Tools",
    slug: "weather-tools",
    desc: "Weather forecasting and climate data",
    icon: <MdWbSunny />,
    tools: [
      {
        name: "Current Weather",
        slug: "current-weather",
        icon: <MdWbSunny />,
        desc: "Get real-time weather updates for any location.",
        code: "currentWeather",
      },
      {
        name: "7-Day Forecast",
        slug: "7-day-forecast",
        icon: <MdWbSunny />,
        desc: "View the weekly weather forecast with temperature trends.",
        code: "sevenDayForecast",
      },
      {
        name: "Air Quality Index",
        slug: "air-quality-index",
        icon: <MdWbSunny />,
        desc: "Check air pollution levels and health advisories.",
        code: "airQualityIndex",
      },
      {
        name: "UV Index Checker",
        slug: "uv-index-checker",
        icon: <MdWbSunny />,
        desc: "Find out the UV radiation risk for your location.",
        code: "uvIndexChecker",
      },
      {
        name: "Wind Speed Calculator",
        slug: "wind-speed-calculator",
        icon: <MdWbSunny />,
        desc: "Measure wind speed and get accurate wind data.",
        code: "windSpeedCalculator",
      },
    ],
  },
  {
    category: "Misc Tools",
    slug: "misc-tools",
    desc: "Various utility tools",
    icon: <MdBuild />,
    tools: [
      {
        name: "Barcode Scanner",
        slug: "barcode-scanner",
        icon: <MdBuild />,
        desc: "Scan barcodes and retrieve product details instantly.",
        code: "barcodeScanner",
      },
      {
        name: "Clipboard Manager",
        slug: "clipboard-manager",
        icon: <MdBuild />,
        desc: "Manage and organize your copied text efficiently.",
        code: "clipboardManager",
      },
    ],
  },
];

export default ToolList;
